app:
  server:
    address: "http://localhost:8080"
spring:
  datasource:
    url: jdbc:h2:mem:test;INIT=create schema if not exists auth\;create schema if not exists public
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: true
    #show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  allowed:
    resources: /h2-console/**
